<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ICMarkets.Models\ICMarkets.Models.csproj" />
    <ProjectReference Include="..\ICMarkets.Repository\ICMarkets.Repository.csproj" />
    <ProjectReference Include="..\ICMarkets.Common\ICMarkets.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
